name: Timer
main: com.leontg77.timer.Main
version: @project.version@
authors:
  - Jim (AnEnragedPigeon)
  - LeonTG
description: Allows creation and management of bossbar timers.
api-version: '1.21.4'

permissions:
  timer.manage:
    description: Allows use of /timer command
    default: op