name: Timer
main: com.leontg77.Main
version: @project.version@
authors:
  - Jim (NotKatuen)
  - LeonTG
description: This plugin adds a timer that will countdown in the boss bar of players.
api-version: '1.17'

commands:
  timer:
    description: Timer command, check usage.