[versions]
pluginYmlPaper = "0.7.1"
paperApi = "1.21.8-R0.1-SNAPSHOT"
placeholderApi = "2.11.6"

[libraries]
paperApi = { group = "io.papermc.paper", name = "paper-api", version.ref = "paperApi" }
placeholderApi = { group = "me.clip", name = "placeholderapi", version.ref="placeholderApi" }

[plugins]
pluginYmlPaper = { id = "de.eldoria.plugin-yml.paper", version.ref = "pluginYmlPaper" }